### ISSUE TITLE
Adjust the dB for pitch changes

### ISSUE THREAD

**Issue by CerenB** [TomasLenc/RhythmCateg#18]
- in the long run (e.g. fMRI exp), keep in mind the energy level for As and Bs should be the same (within 1 run)

**Comment by TomasLenc** [comment]
Atm, if counterbalancing is done, there is exact same physical rms in category A and B. 

But the issue is that across different tone pitches (F0s), the perceived intensity is not equal. This is due to many things, but the main contribution is middle-ear filtering. 
I've previously used this [model from Glasberg and Moore](https://www.psychol.cam.ac.uk/hearing) to equalize loudness across tones with different spectra. 
But we could also just use simple [equal loudness contours](https://au.mathworks.com/matlabcentral/fileexchange/7028-iso-226-equal-loudness-level-contour-signal) to adjust the tone intensity. 

Of course, the physical energy would then be different across different tones, but what we care about is the input brain receives from the auditory nerve. 

Either way, because the pitches are assigned randomly, there should be approx. equal distribution of energy (and tone pitches) across category A and B.

**Comment by CerenB** [comment]
thank you for the info. Looking into those scripts now.

**Comment by CerenB** [comment]
The issue has been carried into the other repo
